name: pangeo
channels:
  - conda-forge
dependencies:
  # CUSTOM STUFF FOR DEP
  # Get some delicious VS Code in there
  - jupyter-vscode-proxy
  # Code formatter and stuff
  - jedi-language-server

  # CUSTOM STUFF FROM MSPC
  - python>=3.10.10
  - pangeo-dask =2024.03.18
  - dask-labextension =7.0.0
  - ipywidgets =8.1.2
  - jupyter-server-proxy =4.1.4
  - jupyterhub-singleuser =4.1.4
  - jupyterlab =4.1.5
  - nbgitpuller =1.2.0

  # OTHER STUFF
  - pip>=20
  - adlfs
  - awscli
  - azure-data-tables
  - boto3
  - bottleneck
  - cartopy
  - cchardet # workaround https://github.com/Azure/azure-sdk-for-python/issues/21516
  - cfgrib>=0.9.9.1
  - ciso
  - click
  - contextily
  - dask-cloudprovider
  - dask-kubernetes
  - azure-cli-core # technically too old: https://github.com/conda-forge/azure-cli-core-feedstock/pull/15
  - msrestazure
  - azure-identity
  - dask-geopandas
  - dask-ml
  - datacube
  - datashader
  - descartes
  - eccodes>=2.24.2
  - eofs
  - erddapy
  - esmpy
  - fastjmd95
  - flox
  - folium
  - fsspec
  - gcsfs
  - geocube
  - geogif
  - geopandas>=0.11.0
  - geoviews-core
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-geopandas
  - intake-xarray
  - ipyleaflet
  - ipywidgets
  - jupyter-panel-proxy
  - jupyter-resource-usage
  - jupyter-server-proxy
  - jupyterlab_code_formatter
  - jupyterlab-geojson
  - jupyterlab-git
  - leafmap>=0.7.6
  - lonboard
  - lz4
  - matplotlib-base
  - metpy
  - nb_conda_kernels
  - nbstripout
  - nc-time-axis
  - netcdf4
  - nomkl
  - numcodecs
  - numpy
  - odc-algo
  - odc-geo
  - odc-stac>=0.3.2
  - pandas>=2.0.0
  - panel
  - papermill
  - parcels
  - pangeo-forge-recipes
  - pint
  - planetary-computer>=0.4.6
  - prefect
  - pyarrow
  - pycamhd
  - pydap
  - pyepsg
  - pystac-client>=0.5.0
  - pystac>=1.1.0
  - python-blosc
  - python-gist
  - python-graphviz
  - python-pdal>=3.1.2
  - rasterio>=1.3.0
  - rechunker
  - rich
  - rio-cogeo
  - rio-tiler
  - rioxarray
  - s3fs>0.5
  - sarsen
  - satpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sparse
  - stac-vrt
  - stac-geoparquet
  - stackstac>=0.4.2
  - tiledb-py
  - voila
  - xarray-sentinel
  - xarray-spatial>=0.2.9
  - xarray>=2023.4.2
  - xarrayutils
  - xcape
  - xclim>=0.43.0
  - xcube
  - xesmf
  - xgcm
  - xmip
  - xhistogram
  - xlayers
  - xmitgcm
  - xpublish
  - xrft
  - zarr
