#!/bin/bash
set -euo pipefail

echo "Installing code-server extensions..."

code-server --install-extension ms-python.python
code-server --install-extension ms-toolsai.jupyter
code-server --install-extension charliermarsh.ruff

echo "Done installing code-server extensions."
